export const SET_IS_CONNECTED = "SET_IS_CONNECTED";
export const FETCH_CASE = "FETCH_CASES";
export const FETCH_CASE_SUCCESS = "FETCH_CASES_SUCCESS";
export const FETCH_CASE_FAILURE = "FETCH_CASES_FAILURE";
