export const SET_IS_CONNECTED = "SET_IS_CONNECTED";
export const FETCH_CASE = "FETCH_CASE";
export const FETCH_CASE_SUCCESS = "FETCH_CASE_SUCCESS";
export const FETCH_CASE_FAILURE = "FETCH_CASE_FAILURE";
export const FETCH_HISTORY = "FETCH_HISTORY";
export const FETCH_HISTORY_SUCCESS = "FETCH_HISTORY_SUCCESS";
export const FETCH_HISTORY_FAILURE = "FETCH_HISTORY_FAILURE";
